# Generated by Django 5.2.7 on 2025-10-29 20:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cargo', '0001_initial'),
        ('dependencia', '0001_initial'),
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='DNI')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('apellidos_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('apellidos_paterno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Paterno')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Teléfono')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de Perfil')),
                ('password_resetada', models.BooleanField(default=False, verbose_name='Password Resetada')),
                ('rol', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('jefe_soporte', 'Jefe de Soporte'), ('ingeniero_soporte', 'Ingeniero de Soporte')], default='usuario', max_length=20, verbose_name='Rol')),
                ('sede_soporte', models.TextField(blank=True, null=True, verbose_name='Sede de Soporte')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo.cargo', verbose_name='Cargo')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dependencia.dependencia', verbose_name='Dependencia')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sede.sede', verbose_name='Sede')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
