# Generated by Django 5.2.7 on 2025-11-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sede_soporte',
        ),
        migrations.AddField(
            model_name='user',
            name='sedes_soporte',
            field=models.ManyToManyField(blank=True, help_text='Selecciona las sedes que este usuario puede soportar', related_name='usuarios_soporte', to='sede.sede', verbose_name='Sedes de Soporte'),
        ),
    ]
