# Generated by Django 5.2.7 on 2025-11-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_sede_soporte_user_sedes_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('jefe_soporte', 'Jefe de Soporte'), ('ingeniero_soporte', 'Ingeniero de Soporte'), ('usuario', 'Usuario')], default='usuario', max_length=20, verbose_name='Rol'),
        ),
    ]
