# Generated by Django 5.2.7 on 2025-11-03 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_rol'),
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_vinculado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene el bot de Telegram vinculado', verbose_name='Bot Vinculado'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID del chat de Telegram del usuario', max_length=50, null=True, unique=True, verbose_name='Chat ID de Telegram'),
        ),
        migrations.CreateModel(
            name='TelegramGrupoSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_chat_id', models.CharField(help_text='ID del grupo de Telegram para esta sede', max_length=50, unique=True, verbose_name='Chat ID del Grupo')),
                ('nombre_grupo', models.CharField(blank=True, help_text='Nombre del grupo en Telegram', max_length=200, null=True, verbose_name='Nombre del Grupo')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el grupo está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_grupo', to='sede.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Grupo de Telegram por Sede',
                'verbose_name_plural': 'Grupos de Telegram por Sede',
                'ordering': ['sede__nombre'],
            },
        ),
    ]
