# Generated by Django 5.2.7 on 2025-11-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='imagenes_urls',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs de las imágenes adjuntas al ticket', verbose_name='URLs de Imágenes'),
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tickets/imagenes/%Y/%m/%d/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ticket.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Imagen de Ticket',
                'verbose_name_plural': 'Imágenes de Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
